### ISSUE TITLE
Agilent module: Don't search for seq/drd interferogram tiles on load.

### ISSUE THREAD

**Issue by stuart-cls** [Quasars/orange-spectroscopy#194]
As suggested by @alexhenderson in #117 , we don't need to have the `.seq` or `.drd` files which only contain interferogram data present to load the agilent processed (`.dat` / `.dmd`) data blocks.

**Comment by AlexHenderson** [comment]
Sorry, probably should have followed this up earlier. Agilent have two file formats for their images: single tile and multi-tile (mosaic). The .seq file only appears in the single-tile format. 
Single-tile format is:
- .bsp (wavenumbers etc); 
- .dat (spectra); 
- .seq (unsure, probably interferograms).

Multi-tile mosaic format is: 
- .dms (summary I think); 
- .dmt (wavenumbers etc, equivalent of .bsp spectral file);
- .drd (interferograms);
- .dmd (spectra).  

Usually, with a multi-tile file collection there is also a .bsp/.dat/.seq file combination that holds the background spectra for each pixel. This is typically a single tile, regardless of how many sample tiles there are in the image since we only need a background for each pixel in the focal plane array detector. This background tile is used in the correction of the transmittance spectra for background effects. Once the data is in absorbance units, the iFFT step and the background step have been completed and so only the .dmt and .dmd files are required to read the spectral image. 

For interested parties, the .bsp and .dmt files appears to be in the Microsoft Compound File Binary File Format. The OpenMCDF project has a download from SourceForge that contains an executable viewer (StucturedStorageExplorer.exe) that might help. https://sourceforge.net/projects/openmcdf/ 

Cheers,
Alex

**Comment by stuart-cls** [comment]
Alex, thank you very much for this message. The pointer to the MCDF is especially helpful!

Best,
Stuart
