### ISSUE TITLE
Multifile: crash when opening files

### ISSUE THREAD

**Issue by ajdapretnar** [Quasars/orange-spectroscopy#431]
Multifile crashes when trying to open files.

It seems like the widget in L319 passes a list of files to open, but then uses `open_filename_dialog` from orange-widget-base that doesn't really support opening multiple files (expects a path, but is given a list of paths instead, filedialogs.py: L168).

I would fix this myself, but I didn't want to touch widget base without consulting first. Should we modify `open_file_dialog` to support opening more then a single file (perhaps with a flag that would allow or disallow opening several files at once)?

**Comment by markotoplak** [comment]
Thanks for reporting this. It is a huge bug.

So the new fixes for guessing extensions broke open_filename_dialog with multiple files. I think it is best to leave the function in Orange as is, because it is mostly used (and tested only) for single files, and I'll make a variant for multiple files and use it myself within spectroscopy.

Anyway I need to do it immediately and re-release, without waiting for a new release of Orange.

**Comment by markotoplak** [comment]
Oh, now I see, thankfully I do not need to hurry that much. It only crashes with the master of widget-base. And I was wondering why the tests did not fail. :)

**Comment by stuart-cls** [comment]
Should we make our upstream master test use the master of the new broken-out parts of Orange like widget-base and canvas-base in addition to Orange itself?

**Comment by markotoplak** [comment]
@stuart-cls, since #434 we also test it with widget-base and canvas-base.

Widget-base has been fixed not to conflict with Multifile.
