### ISSUE TITLE
Preprocess spectra: prepreprocessor list does not expand on orange-widget-base=master

### ISSUE THREAD

**Issue by borondics** [Quasars/orange-spectroscopy#515]
After upgrading to Big Sur (OS X 11.1) I am seeing the left panel of the widget not laid our properly.

Orange: GitHub master

The issue doesn't happen with Quasar 1.0.0

![image](https://user-images.githubusercontent.com/6304794/106398249-1afe6280-6412-11eb-8d77-ee5c0f7d32db.png)

![image](https://user-images.githubusercontent.com/6304794/106398203-c8bd4180-6411-11eb-9895-62856c6d2d53.png)

**Comment by markotoplak** [comment]
Quasar has all packages whose combination was tested. For now, I see two possible causes:

- Some strange Qt problem. In Quasar 1.0.0 package, we distribute 5.12.2, because newer 5.12 have problems with Big Sur.
- If you are using master of orange-widget-base, we changed some left side general settings which could theoretically cause this.

Could you verify which Qt and orange-widget-base versions you have and report on this? If you are on master of orange-widget-base, please also try the older version.

**Comment by markotoplak** [comment]
I tried the master of widget-base and everything seems fine on my Linux computer.

**Comment by markotoplak** [comment]
Correction, the same problems appear also on widget-base = master on my computer, but they are smaller. 

![image](https://user-images.githubusercontent.com/552182/106434373-c38fdf00-6471-11eb-9583-800b94d8ae1b.png)

**Comment by markotoplak** [comment]
Likely cause, for reference: biolab/orange-widget-base#102

**Comment by borondics** [comment]
So, I had PyQt5==5.15 when I took the pictures.

Then I downgraded to 5.12.2 and I still have the same behaviour.

**Comment by markotoplak** [comment]
Related: biolab/orange3#5225

**Comment by markotoplak** [comment]
@borondics, could you check with newest orange-widget-base. I think this should be now fixed.

**Comment by borondics** [comment]
Looks great! (If we don't consider the night mode, but even then maybe it is OK... :D)

Thanks @markotoplak and @irgolic!

![image](https://user-images.githubusercontent.com/6304794/106809186-a9215580-666b-11eb-9717-37fcf394c6cb.png)
